//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS.Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBModel : DbContext
    {
        public DBModel()
            : base("name=DBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_TRN> Employee_TRN { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
    
        public virtual int DeleteContactsByInternalID(Nullable<System.Guid> internalID)
        {
            var internalIDParameter = internalID.HasValue ?
                new ObjectParameter("InternalID", internalID) :
                new ObjectParameter("InternalID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteContactsByInternalID", internalIDParameter);
        }
    }
}
